spring:
  application:
    security:
      jwt:
        secret-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
        expiration: 900000
        refresh-token:
          expiration: 3600000
    name: student-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
  servlet:
    context-path: /api/v1/students/
